### ISSUE TITLE
The extension package does not include the q2q-con-hybercube-qvx connector and instead includes several extensions.

### ISSUE THREAD

**Issue by patrick-ryan1** [q2g/q2g-con-hypercube-qvx#37]
I reviewed each extension folder as well and dont find the connector.

**Comment by konne** [comment]
@AlexanderGoerlich please double check and answer, that also the connctors should be in the package

**Comment by patrick-ryan1** [comment]
Here are extensions in download.

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/17/2018   6:47 PM         698940 q2g-com-picasso.zip
-a----       12/17/2018   6:47 PM        4618284 q2g-ext-alternatestates.zip
-a----       12/17/2018   6:47 PM          33474 q2g-ext-bookmark.zip
-a----       12/17/2018   6:47 PM         121018 q2g-ext-listbox.zip
-a----       12/17/2018   6:47 PM        2677157 q2g-ext-picasso.zip
-a----       12/17/2018   6:47 PM          55023 q2g-ext-scramble.zip
-a----       12/17/2018   6:47 PM          62673 q2g-ext-selector.zip

**Comment by patrick-ryan1** [comment]
It does not appear that @AlexanderGoerlich was able to update this on the site.  I still see same contents today.  You should update contents on Qlik Branch if you are providing a way to build connector only.

**Comment by konne** [comment]
@patrick-ryan1 Because of the holidays it could be that @AlexanderGoerlich missed to fix the download. He will be back in the office starting from tuesday
@patrick-ryan1 I also made some changes, if you like try to download this branch and compile it: https://github.com/q2g/q2g-con-hypercube-qvx/tree/migrateMSBuild We will hopefully migrate this changes next week into the master

**Comment by AlexanderGoerlich** [comment]
@patrick-ryan1 : i have fixed that download
